In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#Importing the dataset

In [5]:
dataset=pd.read_csv('E:\project\AdaptiveHistogram.csv')

In [6]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [7]:
X

array([[  9,   9,   9, ...,  40,  17,   3],
       [  3,   3,   8, ...,  11,  10,   4],
       [  9,   9,   9, ...,  10,   9,   6],
       ...,
       [ 62,  61,  50, ..., 183,  64,  81],
       [ 65,  62,  53, ..., 175, 145,  47],
       [153, 179, 218, ..., 246, 227, 198]], dtype=int64)

In [8]:
y

array(['Covid', 'Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Non-Covid'], dtype=object)

In [9]:
#Splitting training and testing data

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape

(12753, 625)

In [13]:
X_test.shape

(3189, 625)

In [14]:
y_train.shape

(12753,)

In [15]:
y_test.shape

(3189,)

In [16]:
X_train

array([[11, 13, 13, ..., 10,  8,  3],
       [ 9,  8, 10, ..., 10, 10,  7],
       [ 5, 10, 10, ...,  9,  9,  5],
       ...,
       [ 9,  9,  9, ..., 46, 20,  3],
       [11, 11, 11, ...,  6, 10, 11],
       [ 3,  3,  9, ...,  6,  3,  3]], dtype=int64)

In [17]:
X_test

array([[  9,  10,  10, ...,   4,   3,   3],
       [ 43,  70, 200, ..., 183, 174, 162],
       [ 10,  10,  10, ...,   8,  10,  10],
       ...,
       [  9,   9,   9, ...,  10,   9,   9],
       [ 10,  10,  10, ...,  17,  29,  64],
       [ 10,  10,  10, ...,   7,  10,  10]], dtype=int64)

In [18]:
y_train

array(['Non-Covid', 'Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [19]:
y_test

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [22]:
X_train

array([[-0.18340555, -0.17858823, -0.21266643, ..., -0.41738391,
        -0.39689606, -0.44376044],
       [-0.2352387 , -0.29712716, -0.27861928, ..., -0.41738391,
        -0.35598718, -0.3559462 ],
       [-0.338905  , -0.24971159, -0.27861928, ..., -0.43680062,
        -0.37644162, -0.39985332],
       ...,
       [-0.2352387 , -0.27341937, -0.30060357, ...,  0.28161767,
        -0.15144275, -0.44376044],
       [-0.18340555, -0.2260038 , -0.256635  , ..., -0.49505076,
        -0.35598718, -0.26813195],
       [-0.39073815, -0.41566608, -0.30060357, ..., -0.49505076,
        -0.49916828, -0.44376044]])

In [23]:
X_test

array([[-0.2352387 , -0.24971159, -0.27861928, ..., -0.53388418,
        -0.49916828, -0.44376044],
       [ 0.64592487,  1.1727555 ,  3.89839449, ...,  2.94170702,
         2.99854144,  3.04685586],
       [-0.20932212, -0.24971159, -0.27861928, ..., -0.45621733,
        -0.35598718, -0.29008551],
       ...,
       [-0.2352387 , -0.27341937, -0.30060357, ..., -0.41738391,
        -0.37644162, -0.31203907],
       [-0.20932212, -0.24971159, -0.27861928, ..., -0.28146694,
         0.03264723,  0.89540682],
       [-0.20932212, -0.24971159, -0.27861928, ..., -0.47563404,
        -0.35598718, -0.29008551]])

In [24]:
#LDA for dimensionality reduction

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [26]:
lda=LDA(n_components=1)

In [27]:
X_train_lda=lda.fit_transform(X_train,y_train)
X_test_lda=lda.transform(X_test)

In [28]:
lda.n_components

1

In [29]:
X_train_lda

array([[ 2.54385043],
       [-0.6841169 ],
       [-0.2151338 ],
       ...,
       [ 0.28625522],
       [ 0.08080344],
       [ 0.1763998 ]])

In [30]:
X_train_lda.shape

(12753, 1)

In [31]:
X_test_lda

array([[-2.13817761],
       [ 1.86376781],
       [ 0.69183316],
       ...,
       [ 0.42592936],
       [ 0.94435786],
       [-0.99437012]])

In [32]:
X_test_lda.shape

(3189, 1)

In [33]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [ ]:
#Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
logreg = LogisticRegression()
logreg.fit(X_train_lda,y_train)

LogisticRegression()

In [31]:
y_pred_logreg=logreg.predict(X_test_lda)

In [32]:
y_pred_logreg

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [33]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1301,  292],
       [ 262, 1334]], dtype=int64)

In [34]:
accuracy_score(y_test, y_pred_logreg)

0.8262778300407652

In [35]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.8263902988672281

In [36]:
recall_score(y_test, y_pred_logreg,average='weighted')

0.8262778300407652

In [37]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.826260916758009

In [38]:
recall_score(y_test, y_pred_logreg, pos_label='Non-Covid')

0.8358395989974937

In [39]:
specificity=conf_matrix[1,1]/(conf_matrix[1,1]+conf_matrix[1,0])

In [40]:
specificity

0.8358395989974937

In [ ]:
#Naive bayes

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
nb = GaussianNB()
nb.fit(X_train_lda,y_train)

GaussianNB()

In [36]:
y_pred_nb=nb.predict(X_test_lda)

In [37]:
y_pred_nb

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype='<U9')

In [38]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[1324,  269],
       [ 295, 1301]], dtype=int64)

In [39]:
accuracy_score(y_test, y_pred_nb)

0.8231420507996237

In [40]:
precision_score(y_test, y_pred_nb,average='weighted')

0.8232307040480155

In [41]:
recall_score(y_test, y_pred_nb, average='weighted')

0.8231420507996237

In [42]:
f1_score(y_test, y_pred_nb, average='weighted')

0.8231316506563654

In [43]:
recall_score(y_test, y_pred_nb, pos_label='Non-Covid')

0.8151629072681704

In [ ]:
#KNN

In [44]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train_lda,y_train)

KNeighborsClassifier(n_neighbors=6)

In [46]:
y_pred_knn=knn.predict(X_test_lda)

In [47]:
y_pred_knn

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [48]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[1363,  230],
       [ 375, 1221]], dtype=int64)

In [49]:
accuracy_score(y_test, y_pred_knn)

0.8102853559109439

In [50]:
precision_score(y_test, y_pred_knn,average='weighted')

0.8128886208879634

In [51]:
recall_score(y_test, y_pred_knn, average='weighted')

0.8102853559109439

In [52]:
f1_score(y_test, y_pred_knn, average='weighted')

0.8099004894067414

In [ ]:
#Decision tree

In [53]:
from sklearn import tree

In [54]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_lda, y_train)

In [55]:
dt.tree_.node_count

5339

In [56]:
dt.tree_.max_depth

59

In [57]:
y_pred_dt=dt.predict(X_test_lda)

In [58]:
y_pred_dt

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [59]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[1229,  364],
       [ 377, 1219]], dtype=int64)

In [60]:
accuracy_score(y_test, y_pred_dt)

0.7676387582314205

In [61]:
precision_score(y_test, y_pred_dt,average='weighted')

0.7676583318590423

In [62]:
recall_score(y_test, y_pred_dt, average='weighted')

0.7676387582314205

In [63]:
f1_score(y_test, y_pred_dt, average='weighted')

0.7676357879180301

In [64]:
recall_score(y_test, y_pred_dt, pos_label='Non-Covid')

0.7637844611528822

In [ ]:
#Random forest

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
rf = RandomForestClassifier()
rf.fit(X_train_lda, y_train)

RandomForestClassifier()

In [67]:
y_pred_rf=rf.predict(X_test_lda)

In [68]:
y_pred_rf

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [69]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1229,  364],
       [ 377, 1219]], dtype=int64)

In [70]:
accuracy_score(y_test, y_pred_rf)

0.7676387582314205

In [71]:
precision_score(y_test, y_pred_rf,average='weighted')

0.7676583318590423

In [72]:
recall_score(y_test, y_pred_rf, average='weighted')

0.7676387582314205

In [73]:
f1_score(y_test, y_pred_rf, average='weighted')

0.7676357879180301

In [74]:
recall_score(y_test, y_pred_rf, pos_label='Non-Covid')

0.7637844611528822

In [ ]:
#Support vector machine

In [75]:
from sklearn.svm import SVC

In [76]:
svm = SVC()
svm.fit(X_train_lda, y_train)

SVC()

In [77]:
y_pred_svm=svm.predict(X_test_lda)

In [78]:
y_pred_svm

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [79]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1302,  291],
       [ 266, 1330]], dtype=int64)

In [80]:
accuracy_score(y_test, y_pred_svm)

0.8253370962684227

In [81]:
precision_score(y_test, y_pred_svm,average='weighted')

0.8254145183317897

In [82]:
recall_score(y_test, y_pred_svm, average='weighted')

0.8253370962684227

In [83]:
f1_score(y_test, y_pred_svm, average='weighted')

0.8253250729829396

In [84]:
recall_score(y_test, y_pred_svm, pos_label='Non-Covid')

0.8333333333333334

In [ ]:
#Ridge classifier

In [85]:
from sklearn.linear_model import RidgeClassifier

In [86]:
rdgclassifier = RidgeClassifier()
rdgclassifier.fit(X_train_lda, y_train)

RidgeClassifier()

In [87]:
y_pred_rdge=rdgclassifier.predict(X_test_lda)

In [88]:
y_pred_rdge

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype='<U9')

In [89]:
conf_matrix = confusion_matrix(y_test,y_pred_rdge)
conf_matrix

array([[1324,  269],
       [ 296, 1300]], dtype=int64)

In [90]:
accuracy_score(y_test, y_pred_rdge)

0.8228284728755095

In [91]:
precision_score(y_test, y_pred_rdge,average='weighted')

0.8229238853044274

In [92]:
recall_score(y_test, y_pred_rdge, average='weighted')

0.8228284728755095

In [93]:
f1_score(y_test, y_pred_rdge, average='weighted')

0.8228171831211027

In [94]:
recall_score(y_test, y_pred_rdge, pos_label='Non-Covid')

0.8145363408521303