In [3]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv('E:\project\AdaptiveHistogram.csv')

In [5]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [6]:
X

array([[  9,   9,   9, ...,  40,  17,   3],
       [  3,   3,   8, ...,  11,  10,   4],
       [  9,   9,   9, ...,  10,   9,   6],
       ...,
       [ 62,  61,  50, ..., 183,  64,  81],
       [ 65,  62,  53, ..., 175, 145,  47],
       [153, 179, 218, ..., 246, 227, 198]], dtype=int64)

In [7]:
y

array(['Covid', 'Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Non-Covid'], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
X_train.shape

(12753, 625)

In [11]:
X_test.shape

(3189, 625)

In [12]:
y_train.shape

(12753,)

In [13]:
y_test.shape

(3189,)

In [14]:
X_train

array([[11, 13, 13, ..., 10,  8,  3],
       [ 9,  8, 10, ..., 10, 10,  7],
       [ 5, 10, 10, ...,  9,  9,  5],
       ...,
       [ 9,  9,  9, ..., 46, 20,  3],
       [11, 11, 11, ...,  6, 10, 11],
       [ 3,  3,  9, ...,  6,  3,  3]], dtype=int64)

In [15]:
X_test

array([[  9,  10,  10, ...,   4,   3,   3],
       [ 43,  70, 200, ..., 183, 174, 162],
       [ 10,  10,  10, ...,   8,  10,  10],
       ...,
       [  9,   9,   9, ...,  10,   9,   9],
       [ 10,  10,  10, ...,  17,  29,  64],
       [ 10,  10,  10, ...,   7,  10,  10]], dtype=int64)

In [16]:
y_train

array(['Non-Covid', 'Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [17]:
y_test

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [18]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc_X=StandardScaler()
sc_X=sc_X.fit(X_train)

In [21]:
X_train=sc_X.transform(X_train)
X_test=sc_X.transform(X_test)

In [22]:
import pickle

In [23]:
with open("sc_ahnor.pk","wb") as f:
    pickle.dump(sc_X, f)

In [24]:
with open('sc_ahnor.pk', 'rb') as pickle_file:
    sc_X = pickle.load(pickle_file)

In [25]:
sc_X

StandardScaler()

In [26]:
X_train=sc_X.transform(X_train)
X_test=sc_X.transform(X_test)

In [27]:
X_train

array([[-0.47324112, -0.49102337, -0.50313743, ..., -0.61965524,
        -0.56864989, -0.51936325],
       [-0.47458446, -0.49383366, -0.50458736, ..., -0.61965524,
        -0.56781313, -0.51743542],
       [-0.47727114, -0.49270955, -0.50458736, ..., -0.62003225,
        -0.56823151, -0.51839933],
       ...,
       [-0.47458446, -0.4932716 , -0.50507067, ..., -0.60608293,
        -0.56362928, -0.51936325],
       [-0.47324112, -0.49214749, -0.50410405, ..., -0.62116328,
        -0.56781313, -0.51550758],
       [-0.47861447, -0.49664396, -0.50507067, ..., -0.62116328,
        -0.57074181, -0.51936325]])

In [28]:
X_test

array([[-0.47458446, -0.49270955, -0.50458736, ..., -0.62191729,
        -0.57074181, -0.51936325],
       [-0.45174772, -0.458986  , -0.41275871, ..., -0.55443274,
        -0.49919811, -0.44273179],
       [-0.47391279, -0.49270955, -0.50458736, ..., -0.62040926,
        -0.56781313, -0.51598954],
       ...,
       [-0.47458446, -0.4932716 , -0.50507067, ..., -0.61965524,
        -0.56823151, -0.5164715 ],
       [-0.47391279, -0.49270955, -0.50458736, ..., -0.61701618,
        -0.55986382, -0.48996376],
       [-0.47391279, -0.49270955, -0.50458736, ..., -0.62078627,
        -0.56781313, -0.51598954]])

In [29]:
#PCA for dimensionality reduction

In [30]:
from sklearn.decomposition import PCA

In [31]:
pca=PCA(n_components=0.90)

In [32]:
pca_model=pca.fit(X_train)
X_train_pca=pca.transform(X_train)
X_test_pca=pca.transform(X_test)

In [33]:
import pickle

In [34]:
with open("pca_ahnor.pk","wb") as f:
    pickle.dump(pca_model, f)

In [35]:
with open('pca_ahnor.pk', 'rb') as pickle_file:
    pca_model = pickle.load(pickle_file)

In [36]:
pca_model.n_components_

74

In [37]:
X_train_pca=pca_model.transform(X_train)
X_test_pca=pca_model.transform(X_test)

In [38]:
pca.n_components_

74

In [39]:
X_train_pca

array([[-0.09837817, -0.23106547,  0.11796475, ..., -0.05707381,
        -0.01142258, -0.00340511],
       [-0.00112007, -0.18142638,  0.17646203, ..., -0.00819661,
         0.01355098,  0.01651324],
       [-0.24399321, -0.24565285, -0.02895927, ...,  0.00183615,
        -0.00484373, -0.03620048],
       ...,
       [-0.1176533 ,  0.08262782, -0.18045599, ..., -0.00890078,
         0.0062128 ,  0.01342015],
       [-0.10380795,  0.21404693,  0.04667941, ..., -0.00366846,
         0.00048274, -0.0014917 ],
       [-0.16918796, -0.04346456,  0.19946655, ...,  0.00812931,
        -0.00745805, -0.01451397]])

In [40]:
X_train_pca.shape

(12753, 74)

In [41]:
X_test_pca.shape

(3189, 74)

In [42]:
explained_var=pca.explained_variance_ratio_
explained_var

array([0.31696569, 0.08045545, 0.06883431, 0.0479747 , 0.03907482,
       0.0287563 , 0.02791842, 0.02389001, 0.02037653, 0.01436139,
       0.01194045, 0.01154737, 0.01116982, 0.00928326, 0.00912779,
       0.00834205, 0.00800704, 0.00714755, 0.00694503, 0.00660315,
       0.00609148, 0.00570274, 0.00545288, 0.00517022, 0.0050185 ,
       0.00471843, 0.00462321, 0.00437141, 0.00407088, 0.0038354 ,
       0.00374458, 0.00357166, 0.00344844, 0.00333414, 0.00323356,
       0.00306717, 0.00302936, 0.00300363, 0.00287522, 0.0028284 ,
       0.00272816, 0.00255899, 0.00254247, 0.00244441, 0.00235031,
       0.00231661, 0.0022764 , 0.00222302, 0.00212479, 0.00203002,
       0.00196551, 0.00194186, 0.00191478, 0.0018876 , 0.00181057,
       0.00175278, 0.00174002, 0.00168433, 0.00165281, 0.00159968,
       0.00157005, 0.00156189, 0.00154682, 0.00150256, 0.00145979,
       0.00140472, 0.0013937 , 0.00136714, 0.00134043, 0.00132731,
       0.00129479, 0.00126958, 0.00126684, 0.00125528])

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [44]:
#Logistic Regression

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
logreg = LogisticRegression()
logreg.fit(X_train_pca,y_train)

LogisticRegression()

In [47]:
y_pred_logreg=logreg.predict(X_test_pca)

In [48]:
y_pred_logreg

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [49]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1201,  392],
       [ 463, 1133]], dtype=int64)

In [50]:
accuracy_score(y_test, y_pred_logreg)

0.7318908748824082

In [51]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.7323627835843737

In [52]:
recall_score(y_test, y_pred_logreg, average='weighted')

0.7318908748824082

In [53]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.731763534154025

In [54]:
recall_score(y_test, y_pred_logreg, pos_label='Non-Covid')

0.7098997493734336

In [55]:
#Naive Bayes

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
nb = GaussianNB()
nb.fit(X_train_pca,y_train)

GaussianNB()

In [58]:
y_pred_nb=nb.predict(X_test_pca)

In [59]:
y_pred_nb

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype='<U9')

In [60]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[1300,  293],
       [ 945,  651]], dtype=int64)

In [61]:
accuracy_score(y_test, y_pred_nb)

0.6117905299466918

In [62]:
precision_score(y_test, y_pred_nb,average='weighted')

0.6343936169876541

In [63]:
recall_score(y_test, y_pred_nb, average='weighted')

0.6117905299466918

In [64]:
f1_score(y_test, y_pred_nb, average='weighted')

0.5949397607187354

In [65]:
recall_score(y_test, y_pred_nb, pos_label='Non-Covid')

0.40789473684210525

In [64]:
#KNN

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_pca,y_train)

KNeighborsClassifier(n_neighbors=3)

In [68]:
with open("knn_ahnor.pk","wb") as f:
    pickle.dump(knn, f)

In [69]:
with open('knn_ahnor.pk', 'rb') as pickle_file:
    knn = pickle.load(pickle_file)

In [70]:
y_pred_knn=knn.predict(X_test_pca)

In [71]:
y_pred_knn

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [72]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[1591,    2],
       [   5, 1591]], dtype=int64)

In [73]:
accuracy_score(y_test, y_pred_knn)

0.997804954531201

In [74]:
precision_score(y_test, y_pred_knn,average='weighted')

0.9978067206076818

In [75]:
recall_score(y_test, y_pred_knn, average='weighted')

0.997804954531201

In [76]:
f1_score(y_test, y_pred_knn, average='weighted')

0.997804954531201

In [77]:
recall_score(y_test, y_pred_knn, pos_label='Non-Covid')

0.9968671679197995

In [75]:
#Decision Tree

In [76]:
from sklearn import tree

In [77]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_pca, y_train)

In [78]:
with open("dt_ahnor.pk","wb") as f:
    pickle.dump(dt, f)

In [79]:
with open('dt_ahnor.pk', 'rb') as pickle_file:
    dt = pickle.load(pickle_file)

In [80]:
dt.tree_.node_count

1099

In [81]:
dt.tree_.max_depth

27

In [82]:
y_pred_dt=dt.predict(X_test_pca)

In [83]:
y_pred_dt

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [84]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[1505,   88],
       [  88, 1508]], dtype=int64)

In [85]:
accuracy_score(y_test, y_pred_dt)

0.9448102853559109

In [86]:
precision_score(y_test, y_pred_dt,average='weighted')

0.9448102853559109

In [87]:
recall_score(y_test, y_pred_dt, average='weighted')

0.9448102853559109

In [88]:
f1_score(y_test, y_pred_dt, average='weighted')

0.9448102853559109

In [89]:
recall_score(y_test, y_pred_dt, pos_label='Non-Covid')

0.9448621553884712

In [90]:
#Random Forest

In [91]:
from sklearn.ensemble import RandomForestClassifier

In [92]:
rf = RandomForestClassifier()
rf.fit(X_train_pca, y_train)

RandomForestClassifier()

In [93]:
y_pred_rf=rf.predict(X_test_pca)

In [94]:
y_pred_rf

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [95]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1586,    7],
       [   5, 1591]], dtype=int64)

In [96]:
accuracy_score(y_test, y_pred_rf)

0.9962370649106302

In [97]:
precision_score(y_test, y_pred_rf,average='weighted')

0.9962378412029057

In [98]:
recall_score(y_test, y_pred_rf, average='weighted')

0.9962370649106302

In [99]:
f1_score(y_test, y_pred_rf, average='weighted')

0.996237061210485

In [100]:
recall_score(y_test, y_pred_rf, pos_label='Non-Covid')

0.9968671679197995

In [101]:
#Support Vector Machine

In [102]:
from sklearn.svm import SVC

In [103]:
svm = SVC()
svm.fit(X_train_pca, y_train)

SVC()

In [104]:
y_pred_svm=svm.predict(X_test_pca)

In [105]:
y_pred_svm

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [106]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1554,   39],
       [  43, 1553]], dtype=int64)

In [107]:
accuracy_score(y_test, y_pred_svm)

0.9742866102226403

In [108]:
precision_score(y_test, y_pred_svm,average='weighted')

0.9742896556887397

In [109]:
recall_score(y_test, y_pred_svm, average='weighted')

0.9742866102226403

In [110]:
f1_score(y_test, y_pred_svm, average='weighted')

0.9742866001089343

In [111]:
recall_score(y_test, y_pred_svm, pos_label='Non-Covid')

0.9730576441102757

In [112]:
#Ridge Classifier

In [113]:
from sklearn.linear_model import RidgeClassifier

In [114]:
rdgclassifier = RidgeClassifier()
rdgclassifier.fit(X_train_pca, y_train)

RidgeClassifier()

In [115]:
y_pred_rdge=rdgclassifier.predict(X_test_pca)

In [116]:
y_pred_rdge

array(['Covid', 'Non-Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype='<U9')

In [117]:
conf_matrix = confusion_matrix(y_test,y_pred_rdge)
conf_matrix

array([[1203,  390],
       [ 492, 1104]], dtype=int64)

In [118]:
accuracy_score(y_test, y_pred_rdge)

0.7234242709313264

In [119]:
precision_score(y_test, y_pred_rdge,average='weighted')

0.7243589130203579

In [120]:
recall_score(y_test, y_pred_rdge, average='weighted')

0.7234242709313264

In [121]:
f1_score(y_test, y_pred_rdge, average='weighted')

0.7231493808030444

In [122]:
recall_score(y_test, y_pred_rdge, pos_label='Non-Covid')

0.6917293233082706