In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('E:\project\HistogramEqualized.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[ 41,  42,  43, ...,  86,  58,  39],
       [  0,   0,  24, ...,  34,  29,   5],
       [ 39,  38,  37, ...,  36,  36,  21],
       ...,
       [ 11,  10,   8, ..., 182,  43,  89],
       [ 11,   7,   9, ..., 185, 139,  29],
       [164, 184, 215, ..., 250, 239, 224]], dtype=int64)

In [5]:
y

array(['Covid', 'Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Non-Covid'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(12753, 625)

In [9]:
X_test.shape

(3189, 625)

In [10]:
y_train.shape

(12753,)

In [11]:
y_test.shape

(3189,)

In [12]:
X_train

array([[26, 32, 30, ..., 25, 15,  0],
       [16, 14, 17, ..., 15, 15,  9],
       [16, 45, 46, ..., 41, 40, 13],
       ...,
       [39, 41, 41, ..., 93, 59, 31],
       [34, 34, 35, ..., 28, 32, 36],
       [ 0,  2, 24, ..., 10,  0,  0]], dtype=int64)

In [13]:
X_test

array([[ 28,  30,  30, ...,   3,   0,   0],
       [  0,  31, 167, ..., 175, 168, 155],
       [ 26,  26,  28, ...,  24,  25,  26],
       ...,
       [ 39,  39,  39, ...,  39,  36,  35],
       [ 13,  12,  13, ...,  32,  41,  72],
       [ 34,  36,  36, ...,  31,  33,  34]], dtype=int64)

In [14]:
y_train

array(['Non-Covid', 'Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [15]:
y_test

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc_X=StandardScaler()
sc_X=sc_X.fit(X_train)

In [18]:
X_train=sc_X.transform(X_train)
X_test=sc_X.transform(X_test)

In [19]:
import pickle

In [20]:
with open("sc_henor.pk","wb") as f:
    pickle.dump(sc_X, f)

In [21]:
with open('sc_henor.pk', 'rb') as pickle_file:
    sc_X = pickle.load(pickle_file)

In [22]:
sc_X

StandardScaler()

In [23]:
X_train=sc_X.transform(X_train)
X_test=sc_X.transform(X_test)

In [24]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [25]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [26]:
X_train

array([[-0.03172516, -0.03862989, -0.23568232, ..., -0.55060319,
        -0.59743715, -0.74486521],
       [-0.34791067, -0.58730245, -0.61006106, ..., -0.76086003,
        -0.59743715, -0.54446486],
       [-0.34791067,  0.35763363,  0.22509153, ..., -0.21419225,
        -0.05648502, -0.45539804],
       ...,
       [ 0.379316  ,  0.23570639,  0.0810997 , ...,  0.87914331,
         0.35463859, -0.05459734],
       [ 0.22122325,  0.02233373, -0.09169049, ..., -0.48752614,
        -0.2295897 ,  0.05673619],
       [-0.85380749, -0.95308416, -0.40847251, ..., -0.86598845,
        -0.92200842, -0.74486521]])

In [27]:
X_test

array([[ 0.03151194, -0.09959351, -0.23568232, ..., -1.01316824,
        -0.92200842, -0.74486521],
       [-0.85380749, -0.0691117 ,  3.70969371, ...,  2.60324939,
         2.71318985,  2.70647415],
       [-0.03172516, -0.22152074, -0.29327905, ..., -0.57162888,
        -0.3810563 , -0.16593087],
       ...,
       [ 0.379316  ,  0.17474277,  0.02350297, ..., -0.25624362,
        -0.14303736,  0.03446948],
       [-0.44276633, -0.64826607, -0.72525452, ..., -0.40342341,
        -0.03484694,  0.85833759],
       [ 0.22122325,  0.08329735, -0.06289212, ..., -0.42444909,
        -0.20795162,  0.01220278]])

In [28]:
#PCA for dimensionality reduction

In [29]:
from sklearn.decomposition import PCA

In [30]:
pca=PCA(n_components=0.90)

In [31]:
pca_model=pca.fit(X_train)
X_train_pca=pca.transform(X_train)
X_test_pca=pca.transform(X_test)

In [32]:
import pickle

In [33]:
with open("pca_henor.pk","wb") as f:
    pickle.dump(pca_model, f)

In [34]:
with open('pca_henor.pk', 'rb') as pickle_file:
    pca_model = pickle.load(pickle_file)

In [35]:
pca_model.n_components_

73

In [36]:
X_train_pca=pca_model.transform(X_train)
X_test_pca=pca_model.transform(X_test)

In [37]:
pca.n_components_

73

In [38]:
X_train_pca

array([[ -5.84728162,  17.42656919,   1.80926405, ...,   0.89551405,
         -0.46140783,   0.30792577],
       [ -5.51879435,  17.57707635,   1.43580851, ...,  -1.0349049 ,
         -1.18352034,   1.48735306],
       [ -8.06187372,   6.74988081,   7.38563775, ...,   1.06152276,
          0.2526667 ,  -0.11172124],
       ...,
       [  0.21864636, -13.21070857,   1.15703794, ...,  -0.46703081,
         -0.28698138,   0.36789741],
       [ -3.8478824 ,  -9.17412304,  -2.37378789, ...,   0.10853137,
          0.35675031,  -0.94788766],
       [ -9.31000202,   8.82822111,  -2.53700144, ...,  -0.3243463 ,
          0.4711072 ,   0.81589072]])

In [39]:
X_train_pca.shape

(12753, 73)

In [40]:
X_test_pca.shape

(3189, 73)

In [41]:
explained_var=pca.explained_variance_ratio_
explained_var

array([0.25487692, 0.11534218, 0.08564466, 0.05318726, 0.03353602,
       0.02692048, 0.02229275, 0.02174153, 0.01819655, 0.01748911,
       0.01475166, 0.01426554, 0.01300537, 0.01241367, 0.01171681,
       0.01010833, 0.00795285, 0.00763248, 0.00734985, 0.00701217,
       0.00653639, 0.00629736, 0.00604013, 0.00563659, 0.00519366,
       0.00500926, 0.00473305, 0.00434627, 0.00413208, 0.00385885,
       0.00384707, 0.00374322, 0.00362671, 0.00348458, 0.00315416,
       0.0031026 , 0.00302689, 0.00288724, 0.00274255, 0.00267728,
       0.00264267, 0.00259973, 0.00256078, 0.00251819, 0.00244226,
       0.00237497, 0.00231304, 0.00219876, 0.00217198, 0.0021258 ,
       0.00210459, 0.00203968, 0.00202747, 0.00190225, 0.00188461,
       0.00184698, 0.0018277 , 0.00178998, 0.00175705, 0.00165401,
       0.00162925, 0.00160548, 0.00156804, 0.00154236, 0.0015218 ,
       0.00145909, 0.00141576, 0.00140484, 0.00138099, 0.00132944,
       0.00131497, 0.00129192, 0.00127617])

In [42]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [43]:
#Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
logreg = LogisticRegression()
logreg.fit(X_train_pca,y_train)

LogisticRegression()

In [46]:
y_pred_logreg=logreg.predict(X_test_pca)

In [47]:
y_pred_logreg

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Covid', 'Covid'],
      dtype=object)

In [48]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1193,  400],
       [ 477, 1119]], dtype=int64)

In [49]:
accuracy_score(y_test, y_pred_logreg)

0.7249921605518972

In [50]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.7255305473433052

In [51]:
recall_score(y_test, y_pred_logreg, average='weighted')

0.7249921605518972

In [52]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.7248379932065434

In [53]:
recall_score(y_test, y_pred_logreg, pos_label='Non-Covid')

0.7011278195488722

In [54]:
#Naive Bayes

In [55]:
from sklearn.naive_bayes import GaussianNB

In [56]:
nb = GaussianNB()
nb.fit(X_train_pca,y_train)

GaussianNB()

In [57]:
y_pred_nb=nb.predict(X_test_pca)

In [58]:
y_pred_nb

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype='<U9')

In [59]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[1312,  281],
       [ 958,  638]], dtype=int64)

In [60]:
accuracy_score(y_test, y_pred_nb)

0.6114769520225776

In [61]:
precision_score(y_test, y_pred_nb,average='weighted')

0.6361578995660083

In [62]:
recall_score(y_test, y_pred_nb, average='weighted')

0.6114769520225776

In [63]:
f1_score(y_test, y_pred_nb, average='weighted')

0.5932294821695753

In [64]:
recall_score(y_test, y_pred_nb, pos_label='Non-Covid')

0.39974937343358397

In [65]:
#KNN

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_pca,y_train)

KNeighborsClassifier(n_neighbors=3)

In [68]:
with open("knn_henor.pk","wb") as f:
    pickle.dump(knn, f)

In [69]:
with open('knn_henor.pk', 'rb') as pickle_file:
    knn = pickle.load(pickle_file)

In [70]:
y_pred_knn=knn.predict(X_test_pca)

In [71]:
y_pred_knn

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [72]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[1593,    0],
       [   5, 1591]], dtype=int64)

In [73]:
accuracy_score(y_test, y_pred_knn)

0.9984321103794292

In [74]:
precision_score(y_test, y_pred_knn,average='weighted')

0.9984370161667276

In [75]:
recall_score(y_test, y_pred_knn, average='weighted')

0.9984321103794292

In [76]:
f1_score(y_test, y_pred_knn, average='weighted')

0.9984321088377054

In [77]:
recall_score(y_test, y_pred_knn, pos_label='Non-Covid')

0.9968671679197995

In [78]:
#Decision Tree

In [79]:
from sklearn import tree

In [80]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_pca, y_train)

In [81]:
dt.tree_.node_count

1093

In [82]:
dt.tree_.max_depth

26

In [83]:
y_pred_dt=dt.predict(X_test_pca)

In [84]:
y_pred_dt

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [85]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[1490,  103],
       [ 112, 1484]], dtype=int64)

In [86]:
accuracy_score(y_test, y_pred_dt)

0.9325807463154594

In [87]:
precision_score(y_test, y_pred_dt,average='weighted')

0.9325948863280525

In [88]:
recall_score(y_test, y_pred_dt, average='weighted')

0.9325807463154594

In [89]:
f1_score(y_test, y_pred_dt, average='weighted')

0.9325803883260331

In [90]:
recall_score(y_test, y_pred_dt, pos_label='Non-Covid')

0.9298245614035088

In [91]:
#Random Forest

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [93]:
rf = RandomForestClassifier()
rf.fit(X_train_pca, y_train)

RandomForestClassifier()

In [94]:
with open("rf_henor.pk","wb") as f:
    pickle.dump(rf, f)

In [95]:
with open('rf_henor.pk', 'rb') as pickle_file:
    rf = pickle.load(pickle_file)

In [96]:
y_pred_rf=rf.predict(X_test_pca)

In [97]:
y_pred_rf

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [98]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1592,    1],
       [   2, 1594]], dtype=int64)

In [99]:
accuracy_score(y_test, y_pred_rf)

0.9990592662276576

In [100]:
precision_score(y_test, y_pred_rf,average='weighted')

0.9990594630749128

In [101]:
recall_score(y_test, y_pred_rf, average='weighted')

0.9990592662276576

In [102]:
f1_score(y_test, y_pred_rf, average='weighted')

0.9990592664126643

In [103]:
recall_score(y_test, y_pred_rf, pos_label='Non-Covid')

0.9987468671679198

In [104]:
#Support Vector Machine

In [105]:
from sklearn.svm import SVC

In [106]:
svm = SVC(probability=True)
svm.fit(X_train_pca, y_train)

SVC(probability=True)

In [107]:
with open("svm_henor.pk","wb") as f:
    pickle.dump(svm, f)

In [108]:
with open('svm_henor.pk', 'rb') as pickle_file:
    svm = pickle.load(pickle_file)

In [109]:
y_pred_svm=svm.predict(X_test_pca)

In [110]:
y_pred_svm

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [111]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1576,   17],
       [  35, 1561]], dtype=int64)

In [112]:
accuracy_score(y_test, y_pred_svm)

0.9836939479460646

In [113]:
precision_score(y_test, y_pred_svm,average='weighted')

0.9837557682981197

In [114]:
recall_score(y_test, y_pred_svm, average='weighted')

0.9836939479460646

In [115]:
f1_score(y_test, y_pred_svm, average='weighted')

0.9836935150205731

In [116]:
recall_score(y_test, y_pred_svm, pos_label='Non-Covid')

0.9780701754385965

In [117]:
#Ridge Classifier

In [118]:
from sklearn.linear_model import RidgeClassifier

In [119]:
rdgclassifier = RidgeClassifier()
rdgclassifier.fit(X_train_pca, y_train)

RidgeClassifier()

In [120]:
y_pred_rdge=rdgclassifier.predict(X_test_pca)

In [121]:
y_pred_rdge

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Covid', 'Covid'],
      dtype='<U9')

In [122]:
conf_matrix = confusion_matrix(y_test,y_pred_rdge)
conf_matrix

array([[1217,  376],
       [ 512, 1084]], dtype=int64)

In [123]:
accuracy_score(y_test, y_pred_rdge)

0.7215428033866416

In [124]:
precision_score(y_test, y_pred_rdge,average='weighted')

0.7231885646389089

In [125]:
recall_score(y_test, y_pred_rdge, average='weighted')

0.7215428033866416

In [126]:
f1_score(y_test, y_pred_rdge, average='weighted')

0.7210466727822125

In [127]:
recall_score(y_test, y_pred_rdge, pos_label='Non-Covid')

0.6791979949874687