In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
dataset=pd.read_csv('E:\project\HistogramEqualized.csv')

In [12]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [13]:
X

array([[ 41,  42,  43, ...,  86,  58,  39],
       [  0,   0,  24, ...,  34,  29,   5],
       [ 39,  38,  37, ...,  36,  36,  21],
       ...,
       [ 11,  10,   8, ..., 182,  43,  89],
       [ 11,   7,   9, ..., 185, 139,  29],
       [164, 184, 215, ..., 250, 239, 224]], dtype=int64)

In [14]:
y

array(['Covid', 'Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Non-Covid'], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
X_train.shape

(12753, 625)

In [18]:
X_test.shape

(3189, 625)

In [19]:
y_train.shape

(12753,)

In [20]:
y_test.shape

(3189,)

In [21]:
X_train

array([[26, 32, 30, ..., 25, 15,  0],
       [16, 14, 17, ..., 15, 15,  9],
       [16, 45, 46, ..., 41, 40, 13],
       ...,
       [39, 41, 41, ..., 93, 59, 31],
       [34, 34, 35, ..., 28, 32, 36],
       [ 0,  2, 24, ..., 10,  0,  0]], dtype=int64)

In [22]:
X_test

array([[ 28,  30,  30, ...,   3,   0,   0],
       [  0,  31, 167, ..., 175, 168, 155],
       [ 26,  26,  28, ...,  24,  25,  26],
       ...,
       [ 39,  39,  39, ...,  39,  36,  35],
       [ 13,  12,  13, ...,  32,  41,  72],
       [ 34,  36,  36, ...,  31,  33,  34]], dtype=int64)

In [23]:
y_train

array(['Non-Covid', 'Covid', 'Non-Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [24]:
y_test

array(['Covid', 'Non-Covid', 'Covid', ..., 'Covid', 'Non-Covid', 'Covid'],
      dtype=object)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [27]:
X_train

array([[-0.03172516, -0.03862989, -0.23568232, ..., -0.55060319,
        -0.59743715, -0.74486521],
       [-0.34791067, -0.58730245, -0.61006106, ..., -0.76086003,
        -0.59743715, -0.54446486],
       [-0.34791067,  0.35763363,  0.22509153, ..., -0.21419225,
        -0.05648502, -0.45539804],
       ...,
       [ 0.379316  ,  0.23570639,  0.0810997 , ...,  0.87914331,
         0.35463859, -0.05459734],
       [ 0.22122325,  0.02233373, -0.09169049, ..., -0.48752614,
        -0.2295897 ,  0.05673619],
       [-0.85380749, -0.95308416, -0.40847251, ..., -0.86598845,
        -0.92200842, -0.74486521]])

In [28]:
X_test

array([[ 0.03151194, -0.09959351, -0.23568232, ..., -1.01316824,
        -0.92200842, -0.74486521],
       [-0.85380749, -0.0691117 ,  3.70969371, ...,  2.60324939,
         2.71318985,  2.70647415],
       [-0.03172516, -0.22152074, -0.29327905, ..., -0.57162888,
        -0.3810563 , -0.16593087],
       ...,
       [ 0.379316  ,  0.17474277,  0.02350297, ..., -0.25624362,
        -0.14303736,  0.03446948],
       [-0.44276633, -0.64826607, -0.72525452, ..., -0.40342341,
        -0.03484694,  0.85833759],
       [ 0.22122325,  0.08329735, -0.06289212, ..., -0.42444909,
        -0.20795162,  0.01220278]])

In [29]:
#LDA for dimensionality reduction

In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [31]:
lda=LDA(n_components=1)

In [32]:
X_train_lda=lda.fit_transform(X_train,y_train)
X_test_lda=lda.transform(X_test)

In [33]:
lda.n_components

1

In [34]:
X_train_lda

array([[ 2.08862068],
       [-0.76810165],
       [ 0.12803813],
       ...,
       [ 1.00089363],
       [ 0.30212842],
       [ 0.33661582]])

In [35]:
X_train_lda.shape

(12753, 1)

In [36]:
X_test_lda

array([[-2.43298591],
       [ 2.54957241],
       [-0.19514392],
       ...,
       [ 0.40559433],
       [ 0.67165959],
       [-0.89105347]])

In [37]:
X_test_lda.shape

(3189, 1)

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [39]:
#Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
logreg = LogisticRegression()
logreg.fit(X_train_lda,y_train)

LogisticRegression()

In [42]:
y_pred_logreg=logreg.predict(X_test_lda)

In [43]:
y_pred_logreg

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [44]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1313,  280],
       [ 272, 1324]], dtype=int64)

In [45]:
accuracy_score(y_test, y_pred_logreg)

0.8269049858889934

In [46]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.8269123982645716

In [47]:
recall_score(y_test, y_pred_logreg,average='weighted')

0.8269049858889934

In [48]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.8269034880561148

In [49]:
recall_score(y_test, y_pred_logreg, pos_label='Non-Covid')

0.8295739348370927

In [50]:
specificity=conf_matrix[1,1]/(conf_matrix[1,1]+conf_matrix[1,0])

In [51]:
specificity

0.8295739348370927

In [52]:
#Naive Bayes

In [53]:
from sklearn.naive_bayes import GaussianNB

In [54]:
nb = GaussianNB()
nb.fit(X_train_lda,y_train)

GaussianNB()

In [55]:
y_pred_nb=nb.predict(X_test_lda)

In [56]:
y_pred_nb

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype='<U9')

In [57]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[1338,  255],
       [ 305, 1291]], dtype=int64)

In [58]:
accuracy_score(y_test, y_pred_nb)

0.8243963624960803

In [59]:
precision_score(y_test, y_pred_nb,average='weighted')

0.8247208254373967

In [60]:
recall_score(y_test, y_pred_nb, average='weighted')

0.8243963624960803

In [61]:
f1_score(y_test, y_pred_nb, average='weighted')

0.8243557755217906

In [62]:
recall_score(y_test, y_pred_nb, pos_label='Non-Covid')

0.8088972431077694

In [63]:
#KNN

In [64]:
from sklearn.neighbors import KNeighborsClassifier

In [65]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train_lda,y_train)

KNeighborsClassifier(n_neighbors=6)

In [66]:
y_pred_knn=knn.predict(X_test_lda)

In [67]:
y_pred_knn

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[1337,  256],
       [ 376, 1220]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_knn)

0.8018187519598621

In [70]:
precision_score(y_test, y_pred_knn,average='weighted')

0.8035518177127722

In [71]:
recall_score(y_test, y_pred_knn, average='weighted')

0.8018187519598621

In [72]:
f1_score(y_test, y_pred_knn, average='weighted')

0.8015447803218755

In [73]:
recall_score(y_test, y_pred_knn, pos_label='Non-Covid')

0.7644110275689223

In [74]:
#Decision Tree

In [75]:
from sklearn import tree

In [76]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_lda, y_train)

In [77]:
dt.tree_.node_count

5295

In [78]:
dt.tree_.max_depth

64

In [79]:
y_pred_dt=dt.predict(X_test_lda)

In [80]:
y_pred_dt

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Covid', 'Covid'],
      dtype=object)

In [81]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[1251,  342],
       [ 366, 1230]], dtype=int64)

In [82]:
accuracy_score(y_test, y_pred_dt)

0.7779868297271872

In [83]:
precision_score(y_test, y_pred_dt,average='weighted')

0.7780529658068076

In [84]:
recall_score(y_test, y_pred_dt, average='weighted')

0.7779868297271872

In [85]:
f1_score(y_test, y_pred_dt, average='weighted')

0.7779758265256018

In [86]:
recall_score(y_test, y_pred_dt, pos_label='Non-Covid')

0.7706766917293233

In [87]:
#Random Forest

In [88]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
rf = RandomForestClassifier()
rf.fit(X_train_lda, y_train)

RandomForestClassifier()

In [90]:
y_pred_rf=rf.predict(X_test_lda)

In [91]:
y_pred_rf

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Covid', 'Covid'],
      dtype=object)

In [92]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1251,  342],
       [ 366, 1230]], dtype=int64)

In [93]:
accuracy_score(y_test, y_pred_rf)

0.7779868297271872

In [94]:
precision_score(y_test, y_pred_rf,average='weighted')

0.7780529658068076

In [95]:
recall_score(y_test, y_pred_rf, average='weighted')

0.7779868297271872

In [96]:
f1_score(y_test, y_pred_rf, average='weighted')

0.7779758265256018

In [97]:
recall_score(y_test, y_pred_rf, pos_label='Non-Covid')

0.7706766917293233

In [98]:
#Support Vector Machine

In [99]:
from sklearn.svm import SVC

In [100]:
svm = SVC()
svm.fit(X_train_lda, y_train)

SVC()

In [101]:
y_pred_svm=svm.predict(X_test_lda)

In [102]:
y_pred_svm

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype=object)

In [103]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1302,  291],
       [ 263, 1333]], dtype=int64)

In [104]:
accuracy_score(y_test, y_pred_svm)

0.8262778300407652

In [105]:
precision_score(y_test, y_pred_svm,average='weighted')

0.8263756067950475

In [106]:
recall_score(y_test, y_pred_svm, average='weighted')

0.8262778300407652

In [107]:
f1_score(y_test, y_pred_svm, average='weighted')

0.8262630012077977

In [108]:
recall_score(y_test, y_pred_svm, pos_label='Non-Covid')

0.8352130325814536

In [109]:
#Ridge Classifier

In [110]:
from sklearn.linear_model import RidgeClassifier

In [111]:
rdgclassifier = RidgeClassifier()
rdgclassifier.fit(X_train_lda, y_train)

RidgeClassifier()

In [112]:
y_pred_rdge=rdgclassifier.predict(X_test_lda)

In [113]:
y_pred_rdge

array(['Covid', 'Non-Covid', 'Covid', ..., 'Non-Covid', 'Non-Covid',
       'Covid'], dtype='<U9')

In [114]:
conf_matrix = confusion_matrix(y_test,y_pred_rdge)
conf_matrix

array([[1338,  255],
       [ 305, 1291]], dtype=int64)

In [115]:
accuracy_score(y_test, y_pred_rdge)

0.8243963624960803

In [116]:
precision_score(y_test, y_pred_rdge,average='weighted')

0.8247208254373967

In [117]:
recall_score(y_test, y_pred_rdge, average='weighted')

0.8243963624960803

In [118]:
f1_score(y_test, y_pred_rdge, average='weighted')

0.8243557755217906

In [119]:
recall_score(y_test, y_pred_rdge, pos_label='Non-Covid')

0.8088972431077694